### ISSUE TITLE
DBC parsing message

### ISSUE THREAD

**Issue by sskarabej** [bit-dream/candied#48]
**Describe the bug**
DBC parsing issue: All messages with different DBC attributes with the same name, but different values have the same attribute value (the last one declared in the dbc file).
Reason: DBC attributes are copied by reference.

**To Reproduce**

1. Minimal sample of dbc file
```
VERSION ""
NS_ :
	BA_DEF_DEF_
BS_:
BU_:
	GTW

BO_ 696 UI_radarMapData: 8 GTW
BO_ 712 UI_roadCurvature: 8 GTW
BO_ 582 UI_solarData: 5 GTW

BA_DEF_ BO_ "CustomAttr" STRING ;

BA_ "CustomAttr" BO_ 696 "Value1";
BA_ "CustomAttr" BO_ 712 "Value2";
BA_ "CustomAttr" BO_ 582 "Value3";
```

2. Parse dbc file
3. Read `CustomAttr` values from all messages.
4. All messages have the same value of `CustomAttr` (`Value3`).

**Expected behavior**
Expected that each message to have declared value.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.2
 - Browser Chrome 110.0.5481.77 
 - candied v2.1.0., node v16.19.0

**Additional context**

**Comment by bit-dream** [comment]
@sskarabej Sorry for the delay. v2.2.0 is now published on NPM.
