### ISSUE TITLE
Uncaught Error: Number of bits 192 exceeds maximum possible data type.

### ISSUE THREAD

**Issue by Zoheb-Jethwa** [bit-dream/candied#53]
I have used toJson() method to convert .dbc file to json object. but getting below error if file has exceeds192 bits.

Uncaught Error: Number of bits 192 exceeds maximum possible data type
    at computeDataType (candied.js?v=5f239b87:1640:11)
    at DbcParser.addSignal (candied.js?v=5f239b87:1838:23)
    at DbcParser.updateData (candied.js?v=5f239b87:1661:16)
    at candied.js?v=5f239b87:3037:23
    at Array.forEach (<anonymous>)
    at Dbc.load (candied.js?v=5f239b87:3033:11)  

**To Reproduce**
1. Use toJson() on dbc object.
2. Used this snippet : import {Dbc} from 'candied';

const dbc = new Dbc();
const fileContent = dbcReader('tesla_can.dbc');
const data = dbc.load(fileContent)
dbc.toJson({pretty: true}); // Pretty will print the returned json on multiple lines
3. See error which is pasted above

**Expected behavior**
All dbc file should generate Json object irrespective of number of bits.

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [chrome]
 - Version ["candied": "^2.2.0"]

DBC files which are lower than 192 bits working fine.

**Comment by doosuu** [comment]
Bumping this b/c it is quite relevant. The spec doesn't say anything about possible datatypes and therefore any bit size > 64 is allowed, yet candied throws an error. 

@bit-dream any suggestions how to fix this?
2 options that come to my mind:
* Adding an unknown datatype which is inferred in the case of bit size > 64
* Adding a flag to the parsing to turn on/off type computation

**Comment by bit-dream** [comment]
@doosuu I would agree that the spec doesn't necessarily define datatypes. However, I know for Vector's own DBC editor, you can assign pseudo types by specifying whether or not the signal is signed/unsigned/single/double precision. Even for CAN FD within the editor, you can't create signals >64 bits, it will throw an error. The max type you can get is a IEEE double (64bits).

In practice, I don't think I've seen people use signals larger than a double before in CAN. But with that being said, if users have a need for larger types, I think adding an unknown type would be a good path forward. So I would be fine with that approach to give the library more flexibility.

My only concern would be intra-compatibility with bit sets >64. You may not be able to load a .dbc file with signals that large in other dbc applications/libraries. I haven't tried it with Vector's tool, but my gut says it might fail to parse the file.

**Comment by doosuu** [comment]
@bit-dream I understand where you are coming from :-)

Currently, I am faced with a customer DBC file which uses a very large bit size to reserve space in a message until they have fully defined and broken it down. Right now candied refuses to load it. If you are fine with an unknown, I could contribute a pull request to add this feature to the parser.

**Comment by bit-dream** [comment]
@doosuu Yeah, I think I'm fine with the unknown type proposal. If you contribute the change, I'll gladly pull it in.

**Comment by doosuu** [comment]
@bit-dream do you plan to create a new official release sometime soon?
